spring:
  activemq:
    broker-url: tcp://47.98.163.175:61616
    user: admin
    password: admin
    pool:
      enabled: false
    in-memory: true
queue:
  name: queue_name_001
topic:
  name: topic_name_001
server:
  port: 8081